version: '3.5'

networks:
  proxynet:
    name: parkun

services:
  broadcaster:
    image: broadcaster
    restart: always
    networks:
      - proxynet
    volumes:
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
